# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Big.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(230, 130, 321, 521))
        self.groupBox.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.495 rgba(255, 255, 255, 255), stop:0.505 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));")
        self.groupBox.setObjectName("groupBox")
        self.btn2 = QtWidgets.QPushButton(self.groupBox)
        self.btn2.setGeometry(QtCore.QRect(80, 280, 81, 81))
        self.btn2.setStyleSheet("font: 75 26pt \"MS Shell Dlg 2\";\n"
"")
        self.btn2.setObjectName("btn2")
        self.btn1 = QtWidgets.QPushButton(self.groupBox)
        self.btn1.setGeometry(QtCore.QRect(0, 280, 81, 81))
        self.btn1.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"")
        self.btn1.setObjectName("btn1")
        self.btn3 = QtWidgets.QPushButton(self.groupBox)
        self.btn3.setGeometry(QtCore.QRect(160, 280, 81, 81))
        self.btn3.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";\n"
"c")
        self.btn3.setObjectName("btn3")
        self.btnumno = QtWidgets.QPushButton(self.groupBox)
        self.btnumno.setGeometry(QtCore.QRect(240, 280, 81, 81))
        self.btnumno.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"")
        self.btnumno.setObjectName("btnumno")
        self.btn4 = QtWidgets.QPushButton(self.groupBox)
        self.btn4.setGeometry(QtCore.QRect(0, 360, 81, 81))
        self.btn4.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";")
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.groupBox)
        self.btn5.setGeometry(QtCore.QRect(80, 360, 81, 81))
        self.btn5.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";")
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.groupBox)
        self.btn6.setGeometry(QtCore.QRect(160, 360, 81, 81))
        self.btn6.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";")
        self.btn6.setObjectName("btn6")
        self.btn8 = QtWidgets.QPushButton(self.groupBox)
        self.btn8.setGeometry(QtCore.QRect(80, 440, 81, 81))
        self.btn8.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";")
        self.btn8.setObjectName("btn8")
        self.btn7 = QtWidgets.QPushButton(self.groupBox)
        self.btn7.setGeometry(QtCore.QRect(0, 440, 81, 81))
        self.btn7.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";")
        self.btn7.setObjectName("btn7")
        self.btn9 = QtWidgets.QPushButton(self.groupBox)
        self.btn9.setGeometry(QtCore.QRect(160, 440, 81, 81))
        self.btn9.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";")
        self.btn9.setObjectName("btn9")
        self.btnplus = QtWidgets.QPushButton(self.groupBox)
        self.btnplus.setGeometry(QtCore.QRect(240, 440, 81, 81))
        self.btnplus.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";")
        self.btnplus.setObjectName("btnplus")
        self.btnR1 = QtWidgets.QPushButton(self.groupBox)
        self.btnR1.setGeometry(QtCore.QRect(240, 360, 81, 81))
        self.btnR1.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";")
        self.btnR1.setObjectName("btnR1")
        self.btn0 = QtWidgets.QPushButton(self.groupBox)
        self.btn0.setGeometry(QtCore.QRect(0, 200, 81, 81))
        self.btn0.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"")
        self.btn0.setObjectName("btn0")
        self.btnminus = QtWidgets.QPushButton(self.groupBox)
        self.btnminus.setGeometry(QtCore.QRect(240, 200, 81, 81))
        self.btnminus.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";\n"
"")
        self.btnminus.setObjectName("btnminus")
        self.btnravno = QtWidgets.QPushButton(self.groupBox)
        self.btnravno.setGeometry(QtCore.QRect(160, 200, 81, 81))
        self.btnravno.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";\n"
"")
        self.btnravno.setObjectName("btnravno")
        self.btnR = QtWidgets.QPushButton(self.groupBox)
        self.btnR.setGeometry(QtCore.QRect(80, 200, 81, 81))
        self.btnR.setStyleSheet("font: 75 26pt \"MS Shell Dlg 2\";\n"
"")
        self.btnR.setObjectName("btnR")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 0, 321, 201))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.calcul()
        self.ravnore = False

    def calcul(self):
        self.btn0.clicked.connect(lambda: self.wrine_n(self.btn0.text()))
        self.btn1.clicked.connect(lambda: self.wrine_n(self.btn1.text()))
        self.btn2.clicked.connect(lambda: self.wrine_n(self.btn2.text()))
        self.btn3.clicked.connect(lambda: self.wrine_n(self.btn3.text()))
        self.btn4.clicked.connect(lambda: self.wrine_n(self.btn4.text()))
        self.btn5.clicked.connect(lambda: self.wrine_n(self.btn5.text()))
        self.btn6.clicked.connect(lambda: self.wrine_n(self.btn6.text()))
        self.btn7.clicked.connect(lambda: self.wrine_n(self.btn7.text()))
        self.btn8.clicked.connect(lambda: self.wrine_n(self.btn8.text()))
        self.btn9.clicked.connect(lambda: self.wrine_n(self.btn9.text()))
        self.btnminus.clicked.connect(lambda: self.wrine_n(self.btnminus.text()))
        self.btnumno.clicked.connect(lambda: self.wrine_n(self.btnumno.text()))
        self.btnplus.clicked.connect(lambda: self.wrine_n(self.btnplus.text()))
        self.btnR.clicked.connect(lambda: self.wrine_n(self.btnR.text()))
        self.btnR1.clicked.connect(lambda: self.wrine_n(self.btnR1.text()))
        self.btnravno.clicked.connect(self.resultn)

    def resultn(self):
            res = eval(self.label.text())
            self.label.setText("=" + str(res))
            self.ravnore = True

    def wrine_n(self, number):
            if self.label.text() == "0" or self.ravnore:
                self.label.setText(number)
                self.ravnore = False
            else:
                self.label.setText(self.label.text() + number)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GODDAMN It\'s Calculator"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btnumno.setText(_translate("MainWindow", "*"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btnplus.setText(_translate("MainWindow", "+"))
        self.btnR1.setText(_translate("MainWindow", "/"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btnminus.setText(_translate("MainWindow", "-"))
        self.btnravno.setText(_translate("MainWindow", "="))
        self.btnR.setText(_translate("MainWindow", "%"))
        self.label.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
